#!/usr/bin/env node

import { transpileModule } from 'typescript';

function compileTypescript (tsSource) {
  compilerOptions = {
    target: 'es5'
  };

  const jsSource = transpileModule(tsSource, {
    compilerOptions: compilerOptions
  }).outputText;

  return jsSource;
}

let contents = '';

process.stdin.setEncoding('utf8');
process.stdin.on('data', function(data) {
    contents += data;
});
process.stdin.on('end', function () {
    const ts = compileTypescript(contents);
    console.log(ts);
})
process.stdin.resume();
